name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there! Thank you for taking interest in my project :)"
        pr-message: "Hey! Glad to see you here :) If I am not online feel free to contact me by any means necessary :p"
